
# data params
input_dim : 182
sequence_length : 180
behavioral_dim : 2


# mha params
factor_dim : 64
head_dim : 32
num_heads : 2
num_layers : 4
mha_dropout : 0.5
forward_context : 15
backward_context : 35

# ffn params
ffn_dim : 128
ffn_dropout : 0.2

# encoder params
post_readin_dropout : 0.2
post_encoder_dropout : 0.2
post_positional_embedding_dropout : 0.5

# training params
epochs : 750
batch_size : 32
lr_init : 0.0001
weight_decay : 0.000005
loss_balance_factor : 750000
