wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713831156.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.7.16
      5: 0.16.4
      8:
      - 5
      - 13
      13: linux-x86_64
